# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 369f5400c6f95e2c5d7ccfb630a739bd58d8dde979a4a128b89ace7f5bc5bf513bcae5f027adf15e7089b425855ef65ab42152c88fa3cf6c7bbe24714256f736

test:
  secret_key_base: f9794cad9209623f2a79160788259ddff016e553cd4aac56a5fa6e0233f87276053c1f7306adfbf3d643202bb72c92f0f6effc8e9628ad59f13174b216a56ead

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
